---
# Area
- name: area/github
  color: "72ccf3"
  description: >-
    Changes made in the github directory
- name: area/charts
  color: "72ccf3"
  description: >-
    Changes to the charts
- name: area/docs
  color: "72ccf3"
  description: >-
    Changes made to the documentation
- name: area/frontend
  color: "72ccf3"
  description: >-
    Changes made to the frontend
- name: area/backend
  color: "72ccf3"
  description: >-
    Changes made to the backend
- name: area/docker
  color: "72ccf3"
  description: >-
    Changes made to the docker files
- name: area/resources
  color: "72ccf3"
  description: >-
    Changes made in the resources directory
- name: area/test
  color: "72ccf3"
  description: >-
    Changes made to the test

# Features
- name: feature/codebase
  color: "793A6C"
  description: >-
    Feature related to application codebase enhancements
- name: feature/configuration
  color: "793A6C"
  description: >-
    Feature related to application configuration
- name: feature/compatibility
  color: "793A6C"
  description: >-
    Feature related to compatibility with another application or object type
- name: feature/development
  color: "793A6C"
  description: >-
    Feature related to improve the development experience
- name: feature/userinterface
  color: "793A6C"
  description: >-
    Feature related to the user interface

# Renovate
- name: renovate/go
  color: "ffc300"
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"
- name: renovate/helm
  color: "ffc300"
- name: renovate/js
  color: "ffc300"
- name: renovate/go
  color: "ffc300"
# Semantic Type
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"

# Size
- name: size/XS
  color: "009900"
  description: >-
    Denotes a PR that changes 0-9 lines, ignoring generated files.
- name: size/S
  color: "77bb00"
  description: >-
    Denotes a PR that changes 10-29 lines, ignoring generated files.
- name: size/M
  color: "eebb00"
  description: >-
    Denotes a PR that changes 30-99 lines, ignoring generated files.
- name: size/L
  color: "ee9900"
  description: >-
    Denotes a PR that changes 100-499 lines, ignoring generated files.
- name: size/XL
  color: "ee5500"
  description: >-
    Denotes a PR that changes 500-999 lines, ignoring generated files.
- name: size/XXL
  color: "ee0000"
  description: >-
    Denotes a PR that changes 1000+ lines, ignoring generated files.

# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: enhancement
  color: "84b6eb"
- name: link-checker
  color: "7B55D7"
- name: question
  color: "cc317c"
- name: report
  color: "7B55D7"
- name: automated-issue
  color: fef2c0
  description: "Automatic issue. This issue was created by a bot and should not be closed manually."
- name: "stale"
  color: fef2c0
  description: "No activity for quite some time."
- name: "no-stale"
  color: fef2c0
  description: "This is exempt from the stale bot."
- name: "in-progress"
  color: fbca04
  description: "Issue is currently being worked on by a developer."
