---
name: Apply PR Labels

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  labeler:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7
      - name: 🏷️ Apply labels
        uses: actions/labeler@v6
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
